name: ManualBuild

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.14.2'
          modules: 'qtwidgets qtqml'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configure
        run: qmake porymap.pro

      - name: Compile
        run: make

    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built
    #      path: ./porymap.exe
    # can"t find file
    
      - uses: actions/upload-artifact@v2
        with:
          name: porymap_built
          path: /Users/runner/work/porymap/porymap.exe
          
    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built1
    #      path: ./porymap/porymap.exe
    # directory doesn't exist, break the job

    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built2
    #      path: ././porymap
          
    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built3
    #      path: ././porymap.exe
          
    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built4
    #      path: ././porymap/porymap.exe


    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built1
    #      path: /porymap.exe
    # can't find file

    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built2
    #      path: /porymap
    # Can't find file
    
    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built3
    #      path: /
    # Makes job fail and can't access this
  
    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built4
    #      path: /porymap/porymap.exe
    # can't find file

    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: porymap_built5
    #      path: ./
    # can't find file

